//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Ban_Hang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class AdminUser
    {
        [Display(Name = "Mã User")]      
        [Required(ErrorMessage = "ID không được trống .....")]        
        public int ID { get; set; }

        //[RegularExpression(@"^[a-zA-Z][0-9]*$", ErrorMessage = "Tên đăng nhập gồm kí tự in hoa, kí tự in thường, chiều dài tên từ 5 - 20 kí tự ")]
        [Display(Name = "Tên User")]
        [Required(ErrorMessage = "Tên không được trống .....")]
        [StringLength(20, MinimumLength = 5, ErrorMessage = "Chiều dài tên từ 5 - 20 kí tự")]
        public string NameUser { get; set; }
        

        [DisplayName("Vị trí")]
        public string RoleUser { get; set; }

        [RegularExpression("^[a-z0-9]*$", ErrorMessage = "Mật khẩu gồm kí tự in hoa, kí tự thường và số, chiều dài tên từ 8 - 16 kí tự")]
        [DisplayName("Nhập mật khẩu")]
        [Required(ErrorMessage = "Mật khẩu không được trống ....")]
        [StringLength(16, MinimumLength = 8, ErrorMessage = "Chiều dài tên từ 8 - 16 kí tự")]
        [DataType(DataType.Password)]
        public string PasswordUser { get; set; }

        [NotMapped]
        [Compare("PasswordUser")]
        [DisplayName("Nhập lại mật khẩu")]
        public string ConfirmPass { get; set; }
        [NotMapped]
        public string ErrorLogin { get; set; }
    }
}
