//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Ban_Hang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class AdminUser
    {
        [Display(Name = "Mã User")]
        public int ID { get; set; }
        [Required(ErrorMessage = "ID không được trống .....")]

        [Display(Name = "Tên User")]
        public string NameUser { get; set; }
        [Required(ErrorMessage = "Tên không được trống .....")]

        [DisplayName("Vị trí")]
        public string RoleUser { get; set; }

        [DisplayName("Nhập mật khẩu")]
        [Required(ErrorMessage = "Mật khẩu không được trống ....")]
        [DataType(DataType.Password)]
        public string PasswordUser { get; set; }

        [NotMapped]
        [Compare("PasswordUser")]
        [DisplayName("Nhập lại mật khẩu")]
        public string ConfirmPass { get; set; }
        [NotMapped]
        public string ErrorLogin { get; set; }
    }
}
